name: Code quality check on PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '^16.13.1'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --frozen-lockfile

      - name: Check prettier
        run: npx prettier --check $(git diff --cached --name-only HEAD^)

      - name: Check lint
        run: yarn lint
